### ISSUE TITLE
Error fetching license

### ISSUE THREAD

**Issue by Only1KW** [jvolkening/gloc#1]
Attempting to use "GNU/Linux OverDrive/eMusic Client 0.600" to download audio for the first time after just downloading it now.  After opening the odm file I just downloaded from overdrive, I get a list of 6 files to download, with all of them automatically selected.  If I hit "Start Download" I get the following error:

"There was an error fetching the license for this book"

I also see the message "Redundant argument in subroutine entry at ./gloc line 1407" in my terminal, but from looking at the code, that appears to be a side effect, and not the cause of my error.

If I go to File->License Info, The license details show "Yes" or "Unlimited" for all fields except Expiration Date which says "March 11, 2017 13:53:20"

**Comment by jvolkening** [comment]
In most cases this error is due to trying to download a book multiple times, which Overdrive won't let you do from the same ODM file (the XML file that actually gets downloaded to your computer from the Overdrive site). If this is the case, you can usually just re-download the book from their site, which will fetch a new ODM with new license info which should work. GLOC normally caches this information within the download directory so that you can resume a download, etc, without having to re-fetch the license.

If you don't think this is the case (e.g. you didn't try to download the book multiple times using GLOC or other software), try calling GLOC from the command line with the `--debug` flag, open the `*.odm` file for your book and try to download. This will dump some debugging information to the terminal, including the actual error that was received from the Overdrive server when trying to fetch the license. If you do this, please pull the latest version from GithHub as I just now increased the verbosity of the debug output to help with this situation. Feel free to post the output here.

**Comment by Only1KW** [comment]
Originally, I had downloaded two different .odm files for the same book due to trying to figure out how to open it originally.  After reading your comments, I figured my problem was going to be that I opened the older download and I needed to use the newer download.  However, after trying to open both downloaded .odm files, and then trying to download fresh today and open it again, I continue to get the same error.  Here is the error I get with --debug:

[Only1KW@crono gloc-master]$ ./gloc --debug
CLID: 0E3B557A-7BB3-0B6E-3C9EDD40F7C2B998A
set CL to 0E3B557A-7BB3-0B6E-3C9EDD40F7C2B998A
sha1: 9676436dcf37ceee921ac9c23040e5cfe538b64f
changing to /home/Only1KW/Downloads/Bringing_Up_Boys/
download dir: /home/Only1KW/Downloads/Bringing_Up_Boys/
thumb: folder.jpg
fetching thumbnail from server: https://images.contentreserve.com/ImageType-100/0457-1\{B0E62BAA-9217-483F-BD4E-246DD5A2F6FD}Img100.jpg
Internal Exception
fetching thumbnail from server: https://images.contentreserve.com/ImageType-200/0457-1\{B0E62BAA-9217-483F-BD4E-246DD5A2F6FD}Img200.jpg
Internal Exception
LICENSE: https://ofs.contentreserve.com/MP3LicenseAcquisitionService.svc/4a363d9d-9130-4985-95ba-a72601518e50?MediaID=b0e62baa-9217-483f-bd4e-246dd5a2f6fd-425&ClientID=0E3B557A-7BB3-0B6E-3C9EDD40F7C2B998A&OMC=3.1.0.1&OS=5.1.2.2600.SP2&Hash=QslnK2TC/6UPNjBQLjijrLFnn7s=
error fetching license: Internal Exception
Redundant argument in subroutine entry at ./gloc line 1407.

**Comment by jvolkening** [comment]
This doesn't look like the license issue I described. It appears that all attempts to download content are failing (even the thumbnails, which shouldn't be protected in any way). Am I correct in assuming that the book thumbnail doesn't show up in the GUI? The "Internal Exception" error is from the underlying library that handles the HTTP/S connection. This can be caused by a number of things, including a simple network timeout. Are you by any chance operating behind a firewall with strict outgoing rules, or perhaps a strict AppArmor/SELinux security policy regarding networking? 

Can you try downloading the latest commit of GLOC from this repo which I mentioned above, retry and report the STDERR? That will dump additional details about the internal exception which may help. At this point there is no need to re-download any new ODMs because the errors you're seeing appear to be caused by a more fundamental issue with networking.

**Comment by jvolkening** [comment]
> I also see the message "Redundant argument in subroutine entry at ./gloc line 1407" in my terminal, but from looking at the code, that appears to be a side effect, and not the cause of my error.

By the way, thanks for pointing this out -- should be fixed in latest commit.

**Comment by Only1KW** [comment]
> Am I correct in assuming that the book thumbnail doesn't show up in the GUI?

Yes.

> Are you by any chance operating behind a firewall with strict outgoing rules, or perhaps a strict AppArmor/SELinux security policy regarding networking?

No, I am running a standard install without setting up any special firewall rules that I am aware of.  I've never had any networking issues in the past that ended up being the result of any firewall issues before.

> Can you try downloading the latest commit of GLOC from this repo which I mentioned above, retry and report the STDERR?

I did re-download the latest commit of GLOC before running it and posting the earlier error I got.  However, it appears my terminal was still using a cached version of the old file for some reason and I needed to exit and re-enter the folder in my terminal to get it to reload again.  After running it again, I got the following output (in part):
`error fetching license: Internal Exception
IO::Socket::SSL 1.42 must be installed for https support
Net::SSLeay 1.49 must be installed for https support`

Neither seem to be in the list of suggested modules to install.  I installed those and then got the following error:
`error fetching license: Not Found
<LicenseError xmlns="http://license.overdrive.com/2008/03/LicenseError.xsd" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><ErrorCode>1003</ErrorCode><ErrorMessage>The requested license is either invalid or already acquired</ErrorMessage><ErrorDetails i:nil="true"/></LicenseError>`

I tried downloading the .odm file again and re-running gloc, and that attempt was successful in pulling down the mp3s!

You probably want to add the additional modules to the list in the documentation, but otherwise, I consider this issue fixed.  Thanks for your help!

**Comment by jvolkening** [comment]
Thanks for the feedback. I will definitely update the docs and also add an explicit check for HTTPS capability on startup.

Please let me know if you notice any more bugs or quirks. I've been using the code in one form or another for at least ten years but the user base is small and these sorts of things can be hard to spot without other people running it on diverse systems.
